id = "olus-lang"
name = "Oluś"
version = "0.0.1"
schema_version = 1
authors = ["Remco Bloemen <Remco@wicked.ventures>"]
description = "Zed Extension for the Oluś Language."
repository = "https://github.com/recmo/olus"

[grammars.olus]
repository = "https://github.com/recmo/olus"
commit = "d8a1ab16bf61d9c1ba41c868f4dfb43f8385a469"
path = "editor-support/tree-sitter-olus"
